import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.MaterialsCarbonNanotubesFullerenesTheoremCanonicalLaneLean.AdmissibleClass
import HautevilleHouse.MaterialsCarbonNanotubesFullerenesTheoremCanonicalLaneLean.BridgeLemmas
import HautevilleHouse.MaterialsCarbonNanotubesFullerenesTheoremCanonicalLaneLean.GateLemmas

namespace HautevilleHouse
namespace MaterialsCarbonNanotubesFullerenesTheoremCanonicalLaneLean

def ConstrainedMaterialsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_materials_endgame (A : AdmissibleClass) :
  ConstrainedMaterialsClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end MaterialsCarbonNanotubesFullerenesTheoremCanonicalLaneLean
end HautevilleHouse